### ISSUE TITLE
TypeError no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by sergio-bobillier** [googleplus/gplus-verifytoken-ruby#3]
The example application no longer works because the google-id-token gem is outdated. The `JWT.decode` function now returns an `Array` instead of a `Hash` so on line 110 a `TypeError: no implicit conversion of String into Integer` is thrown:

https://code.google.com/p/google-id-token/source/browse/lib/google-id-token.rb#110

Seggested fix:

Eihter update the google-id-token gem or use the Nerian fork: https://github.com/Nerian/google-id-token

**Comment by gguuss** [comment]
Just fixed this, please reopen if the issue persists.
